services:
  postgres:
    image: postgres:17-alpine
    container_name: block1_postgres
    restart: always
    environment:
      POSTGRES_DB: block1_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    ports:
      - "8877:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: block1_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: block1_db
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: